on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      kubekube_pat:
        required: true
      slack_webhook:
        required: true

jobs:
  run-kubekube-edit:
    runs-on: [ self-hosted, default ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'dunamu-fd/kubekube'
          ref: master
          token: ${{ secrets.kubekube_pat }}
      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1
      - name: Edit image tag
        run: |
          kustomize edit set image r.upbit.io/${{ inputs.image_name }}:${{ inputs.tag }}
        working-directory: ./dev/recipes/ns-opp-omega/recipes0/kong
      - name: Set git user
        run: |
          git config user.name $GIT_USER_NAME
          git config user.email $GIT_USER_EMAIL
        env:
          GIT_USER_NAME: 'github-actions[bot]'
          GIT_USER_EMAIL: 'github-actions[bot]@users.noreply.github.com'
      - name: Commit changes
        run: |
          git pull origin $BRANCH_NAME
          git add .
          git commit -m "$COMMIT_MESSAGE"
          git push origin $BRANCH_NAME
        env:
          BRANCH_NAME: master
          COMMIT_MESSAGE: ':bookmark: [dev] kong-ui service tag 수정'
      
  noti:
    needs: run-kubekube-edit
    runs-on: [self-hosted, default]
    steps:
      - name: Slack notification
        uses: rtCamp/action-slack-notify@12e36fc18b0689399306c2e0b3e0f2978b7f1ee7
        env:
          SLACK_USERNAME: 'kong-ui-ci'
          SLACK_CHANNEL: '#op-platform-bravo-deploy'
          SLACK_COLOR: ${{ needs.run-kubekube-edit.result }}
          SLACK_ICON_EMOJI: ${{ needs.run-kubekube-edit.result == 'success' && ':art:' || ':x:' }}
          SLACK_WEBHOOK: ${{ secrets.slack_webhook }}
          SLACK_MESSAGE: ${{ needs.run-kubekube-edit.result == 'success' && 'Kong-UI CD 완료' || '<@U03ENQ74S9K> <@U02RRJM4ST1> <@U02SJSA85R7> @etham @den @koon Kong-UI CD 실패' }}
          SLACK_LINK_NAMES: true

