name: DEVELOP CI & CD
on:
  push:
    branches: [develop]

jobs:
  ci:
    uses: dunamu-fd/kong-ui/.github/workflows/_ci.yaml@develop
    with:
      tag: ${{ github.run_number }}
    secrets:
      harbor_username: ${{ secrets.HARBOR_USERNAME }}
      harbor_password: ${{ secrets.HARBOR_PASSWORD }}
      slack_webhook: ${{ secrets.BRAVO_DEPLOY_SLACK_WEB_HOOK }}
    
  cd:
    needs: ci
    uses: dunamu-fd/kong-ui/.github/workflows/_cd.yaml@develop
    with:
      image_name: opp-omega.dna/kong-ui
      tag: ${{ github.run_number }}
    secrets:
      kubekube_pat: ${{ secrets.KUBEKUBE_DEPLOYER }}
      slack_webhook: ${{ secrets.BRAVO_DEPLOY_SLACK_WEB_HOOK }}
